services:
  - type: web
    name: location-ybmtl
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20"
